"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Row = { id: string; caseNumber: string; createdAt: string; stateCode: string | null; districtCode: string | null; threatCategory: string | null; riskLevel: string | null; govStatus: string; assignedOfficer: { fullName: string | null; officerCode: string | null } | null };
type Result = { rows: Row[]; total: number; page: number; pageSize: number };

/** Privacy-safe default case list: all filtering/paging stays server-side. */
export function GovCaseExplorer() {
  const [result, setResult] = useState<Result | null>(null); const [q, setQ] = useState(""); const [page, setPage] = useState(1); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setError(null); const p = new URLSearchParams({ page: String(page), pageSize: "25" }); if (q.trim()) p.set("q", q.trim()); const res = await fetch(`/gov/api/cases?${p}`, { cache: "no-store" }); if (!res.ok) throw new Error(`Unable to load cases (${res.status}).`); setResult(await res.json()); }, [page, q]);
  useEffect(() => { void load().catch(e => setError(e.message)); }, [load]);
  const rows = result?.rows ?? []; const last = result ? Math.max(1, Math.ceil(result.total / result.pageSize)) : 1;
  return <section className="gov-panel space-y-5 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-lg font-bold text-slate-100">Case Explorer</h2><p className="text-sm text-slate-500">Privacy-safe list: no victim PII or precise locations.</p></div><form onSubmit={e => { e.preventDefault(); setPage(1); void load().catch(err => setError(err.message)); }} className="flex gap-2"><input value={q} onChange={e => setQ(e.target.value)} maxLength={160} placeholder="Case ID, indicator, email, URL…" className="w-64 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100"/><button className="rounded-lg bg-teal-500 px-3 py-2 text-sm font-bold text-slate-950">Search</button></form></div>{error && <p className="text-sm text-rose-300">{error}</p>}<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-700 text-xs uppercase text-slate-500"><tr><th className="p-2">Case ID</th><th>Date</th><th>State / District</th><th>Threat</th><th>Risk</th><th>Status</th><th>Assigned</th></tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-b border-slate-800 text-slate-300"><td className="p-2 font-mono text-teal-300"><Link href={`/gov/cases/${row.id}`}>{row.caseNumber}</Link></td><td>{new Date(row.createdAt).toLocaleDateString("en-IN")}</td><td>{row.stateCode ?? "—"} / {row.districtCode ?? "—"}</td><td>{row.threatCategory ?? "—"}</td><td>{row.riskLevel ?? "Unset"}</td><td>{row.govStatus}</td><td>{row.assignedOfficer?.fullName ?? "Unassigned"}</td></tr>)}{result && rows.length === 0 && <tr><td colSpan={7} className="p-8 text-center text-slate-500">No scoped cases match the current filter.</td></tr>}</tbody></table></div><div className="flex items-center justify-between text-sm text-slate-400"><span>{result ? `${result.total} scoped case${result.total === 1 ? "" : "s"}` : "Loading…"}</span><span className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(p => p - 1)} className="rounded border border-slate-700 px-2 py-1 disabled:opacity-40">Previous</button><span className="px-1 py-1">{page} / {last}</span><button disabled={page >= last} onClick={() => setPage(p => p + 1)} className="rounded border border-slate-700 px-2 py-1 disabled:opacity-40">Next</button></span></div></section>;
}
