"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Case = { id: string; caseNumber: string | null; stateCode: string | null; districtCode: string | null; threatCategory: string | null; createdAt: string | null; riskLevel?: string | null; govStatus?: string };
type Indicator = { type: string; value: string; firstSeen: string | null; lastSeen: string | null; caseCount: number; confidence: number | null; states: Array<{ code: string | null; count: number }>; categories: Array<{ label: string | null; count: number }>; cases: Case[] };

export function GovIndicatorView() {
  const [query, setQuery] = useState(""); const [results, setResults] = useState<Indicator[] | null>(null); const [error, setError] = useState<string | null>(null);
  const search = async (event: FormEvent) => { event.preventDefault(); if (!query.trim()) return; setError(null); const response = await fetch(`/gov/api/indicators?q=${encodeURIComponent(query.trim())}`, { cache: "no-store" }); if (!response.ok) { setError(`Indicator search failed (${response.status}).`); return; } setResults(await response.json()); };
  return <div className="space-y-5"><section className="gov-panel p-5"><h2 className="text-xl font-bold text-slate-100">Indicator Intelligence</h2><p className="mt-1 text-sm text-slate-400">IP, domain, URL, email, phone, and hash correlations across your server-scoped cases.</p><form onSubmit={search} className="mt-4 flex max-w-xl gap-2"><input value={query} onChange={(e) => setQuery(e.target.value)} maxLength={320} placeholder="Search an exact indicator value" className="min-w-0 flex-1 rounded border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-100"/><button className="rounded bg-teal-500 px-4 py-2 text-sm font-bold text-slate-950">Search</button></form>{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}</section>{results?.map((item) => <section key={`${item.type}:${item.value}`} className="gov-panel p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs text-teal-300">{item.type}</p><h3 className="break-all font-bold text-slate-100">{item.value}</h3></div><p className="rounded border border-amber-400/30 bg-amber-400/10 px-3 py-1.5 text-xs text-amber-100">Possible shared indicator, observed in {item.caseCount} case{item.caseCount === 1 ? "" : "s"}</p></div><div className="mt-4 grid gap-4 md:grid-cols-3 text-sm"><div><p className="text-slate-500">First / last seen</p><p className="mt-1 text-slate-200">{item.firstSeen ? new Date(item.firstSeen).toLocaleDateString("en-IN") : "—"} · {item.lastSeen ? new Date(item.lastSeen).toLocaleDateString("en-IN") : "—"}</p></div><div><p className="text-slate-500">States</p><p className="mt-1 text-slate-200">{item.states.map((x) => `${x.code ?? "Unknown"} (${x.count})`).join(", ") || "—"}</p></div><div><p className="text-slate-500">Categories</p><p className="mt-1 text-slate-200">{item.categories.map((x) => `${x.label ?? "Other"} (${x.count})`).join(", ") || "—"}</p></div></div><ul className="mt-4 divide-y divide-slate-800">{item.cases.map((c) => <li key={c.id} className="py-2 text-sm text-slate-300"><Link className="font-mono text-teal-300" href={`/gov/cases/${c.id}`}>{c.caseNumber ?? c.id}</Link><span className="ml-3 text-slate-500">{c.stateCode ?? "—"} / {c.districtCode ?? "—"} · {c.threatCategory ?? "Unclassified"}</span></li>)}</ul></section>)}{results?.length === 0 && <section className="gov-panel p-6 text-center text-sm text-slate-500">No scoped cases contain that indicator.</section>}</div>;
}

type QueueResult = { view: string; rows: Array<Case & { riskLevel: string | null; govStatus: string; assignedOfficer: { fullName: string | null; officerCode: string | null } | null }> };
export function GovQueueView() {
  const [view, setView] = useState<"NEW" | "TRIAGED" | "PRIORITY">("NEW"); const [data, setData] = useState<QueueResult | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setError(null); const response = await fetch(`/gov/api/queue?view=${view}&pageSize=100`, { cache: "no-store" }); if (!response.ok) throw new Error(`Unable to load queue (${response.status}).`); setData(await response.json()); }, [view]);
  useEffect(() => { void load().catch((e) => setError(e.message)); }, [load]);
  return <div className="space-y-5"><section className="gov-panel p-5"><h2 className="text-xl font-bold text-slate-100">Investigation Queue</h2><p className="mt-1 text-sm text-slate-400">Cases are ordered server-side and limited to your jurisdiction or assignment scope.</p><div className="mt-4 flex gap-2">{(["NEW", "TRIAGED", "PRIORITY"] as const).map((key) => <button key={key} type="button" onClick={() => setView(key)} className={`rounded px-3 py-1.5 text-xs font-semibold ${view === key ? "bg-teal-500 text-slate-950" : "border border-slate-700 text-slate-300"}`}>{key === "PRIORITY" ? "Risk priority" : key[0] + key.slice(1).toLowerCase()}</button>)}</div></section>{error ? <section className="gov-panel p-5 text-rose-300">{error}</section> : <section className="gov-panel overflow-x-auto p-5"><table className="w-full text-left text-sm"><thead className="border-b border-slate-700 text-xs uppercase text-slate-500"><tr><th className="p-2">Case</th><th>Location</th><th>Threat</th><th>Risk</th><th>Status</th><th>Assigned</th></tr></thead><tbody>{data?.rows.map((row) => <tr key={row.id} className="border-b border-slate-800 text-slate-300"><td className="p-2"><Link className="font-mono text-teal-300" href={`/gov/cases/${row.id}`}>{row.caseNumber ?? row.id}</Link></td><td>{row.stateCode ?? "—"} / {row.districtCode ?? "—"}</td><td>{row.threatCategory ?? "Unclassified"}</td><td>{row.riskLevel ?? "Unset"}</td><td>{row.govStatus}</td><td>{row.assignedOfficer?.fullName ?? "Unassigned"}</td></tr>)}{data && data.rows.length === 0 && <tr><td colSpan={6} className="p-8 text-center text-slate-500">No scoped cases in this queue.</td></tr>}</tbody></table></section>}</div>;
}

type Trends = { totals: { total: number; prevPeriod: number; changePct: number | null }; casesOverTime: Array<{ day: string; count: number }>; byStatus: Array<{ label: string; count: number }>; byThreat: Array<{ label: string; count: number }>; byState: Array<{ label: string; count: number }>; indicatorRecurrence: Array<{ value: string; type: string; cases: number }> };
export function GovTrendsView() {
  const [days, setDays] = useState(30); const [data, setData] = useState<Trends | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setError(null); const response = await fetch(`/gov/api/trends?days=${days}`, { cache: "no-store" }); if (!response.ok) throw new Error(`Unable to load trends (${response.status}).`); setData(await response.json()); }, [days]);
  useEffect(() => { void load().catch((e) => setError(e.message)); }, [load]); const max = Math.max(1, ...(data?.casesOverTime ?? []).map((x) => x.count)); const emerging = data?.totals.changePct !== null && (data?.totals.changePct ?? 0) >= 30;
  const list = (items: Array<{ label: string; count: number }>) => <ul className="mt-3 space-y-2">{items.map((x) => <li key={x.label} className="flex items-center gap-2 text-sm"><span className="w-32 truncate text-slate-300">{x.label}</span><span className="h-2 flex-1 rounded bg-slate-800"><span className="block h-full rounded bg-teal-400/70" style={{ width: `${(x.count / Math.max(1, ...items.map((i) => i.count))) * 100}%` }}/></span><span className="font-mono text-slate-400">{x.count}</span></li>)}</ul>;
  return <div className="space-y-5"><section className="gov-panel p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-100">Analytics & Trends</h2><p className="mt-1 text-sm text-slate-400">An emerging label requires at least 30% growth over the preceding equal period.</p></div><select value={days} onChange={(e) => setDays(Number(e.target.value))} className="rounded border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-slate-200"><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select></div></section>{error ? <section className="gov-panel p-5 text-rose-300">{error}</section> : data && <><section className="grid gap-4 sm:grid-cols-3"><article className="gov-panel p-4"><p className="text-xs text-slate-500">Cases in period</p><p className="mt-2 font-mono text-3xl text-slate-100">{data.totals.total}</p></article><article className="gov-panel p-4"><p className="text-xs text-slate-500">Previous period</p><p className="mt-2 font-mono text-3xl text-slate-100">{data.totals.prevPeriod}</p></article><article className="gov-panel p-4"><p className="text-xs text-slate-500">Period change</p><p className="mt-2 font-mono text-3xl text-slate-100">{data.totals.changePct === null ? "—" : `${data.totals.changePct}%`}</p>{emerging && <p className="mt-1 text-xs text-amber-200">Emerging: threshold met</p>}</article></section><section className="gov-panel p-5"><h3 className="font-bold text-slate-100">Cases over time</h3><div className="mt-4 flex h-44 items-end gap-1">{data.casesOverTime.map((x) => <div key={x.day} title={`${x.day}: ${x.count}`} className="min-w-2 flex-1 rounded-t bg-teal-400/70" style={{ height: `${Math.max(3, (x.count / max) * 100)}%` }}/>)}</div><p className="mt-2 text-xs text-slate-500">Each bar is one day; hover for the live count.</p></section><section className="grid gap-5 lg:grid-cols-3"><article className="gov-panel p-5"><h3 className="font-bold text-slate-100">Threat categories</h3>{list(data.byThreat)}</article><article className="gov-panel p-5"><h3 className="font-bold text-slate-100">Statuses</h3>{list(data.byStatus)}</article><article className="gov-panel p-5"><h3 className="font-bold text-slate-100">States</h3>{list(data.byState)}</article></section><section className="gov-panel p-5"><h3 className="font-bold text-slate-100">Recurring indicators</h3><ul className="mt-3 divide-y divide-slate-800">{data.indicatorRecurrence.map((x) => <li key={`${x.type}:${x.value}`} className="flex justify-between gap-3 py-2 text-sm"><span className="truncate text-slate-300">{x.type}: {x.value}</span><span className="text-amber-200">Possible shared indicator, observed in {x.cases} cases</span></li>)}{data.indicatorRecurrence.length === 0 && <li className="py-4 text-sm text-slate-500">No recurring indicators in this period.</li>}</ul></section></>}</div>;
}
